"use client"
import type { Metadata } from 'next'
import '../styles/global.scss'
import Script from 'next/script'
import Header from '@/components/header'
import Footer from '@/components/footer'


// export const metadata: Metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* Lottie Animation Loader */}
      <Script src="https://unpkg.com/@lottiefiles/lottie-player@0.4.0/dist/lottie-player.js" />
      {/* Smooth Scrolling */}
      <Script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@15/dist/smooth-scroll.polyfills.min.js" />
      {/* Icons */}
      <Script src="https://kit.fontawesome.com/da815149ed.js" />
      <body>
        <div className="outer-wrapper">
          <div className="main-container">
            <Header />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
